server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Taipei
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  cache:
    type: redis
  redis:
    port: 6379
    host: localhost

#logging:
#  group:
#    mygroup1: org.tutorial.aop,org.tutorial.controller
#    mygroup2: org.tutorial.repository,com.mysql
#  level:
#    root: info
#    # 可指定特定包或是組的輸出級別
#    mygroup1: debug
#    
#    '[org.tutorial.service]': warn
#  # 輸出文件(可定義副檔名)
#  file:
#    name: mylog.log
#  # 超過一定大小存檔後再輸出
#  logback:
#    rollingpolicy:
#      max-file-size: 15KB
#      file-name-pattern: mylog.%d{yyyy-MM-dd}.%i.log